### ISSUE TITLE
Please Add Import and Search Option

### ISSUE THREAD

**Issue by IplaygamesIhate** [noahm/contactful#1]
I have been looking for contact manager for a long time. I really like yours. I would like to continue using it.

Please Add Import and Search Option. I have 100's of contact and these feature would help very much

**Comment by noahm** [comment]
I do plan on adding an import option soon! Just out of curiosity, where would you be importing contacts from? Do you know what formats I would need to accept to allow you to import?

**Comment by IplaygamesIhate** [comment]
I would be importing my contacts from outlook contacts. In my case it's a .csv file. Thank you for your reply. Looking forward to this feature.

My bad that I missed the search option like an idiot. 

![image](https://user-images.githubusercontent.com/92145260/157110648-eff969b4-f8bf-417b-b0dc-cf32985a1fe4.png)

**Comment by noahm** [comment]
@IplaygamesIhate I've added an import feature for outlook csv import in #2. I don't know how soon I can update this on Deta Space (update process is not entirely self-service yet) but if you're self-hosting I'd love to get feedback from you on how well it works!

**Comment by noahm** [comment]
These changes are now available to install on Deta Space as well. Update wherever you're using it and let me know how it works out for you!

**Comment by IplaygamesIhate** [comment]
Thank you for the update man. 

I just imported my contacts on Deta and it worked like charm. I'll be using this more regularly now and I plan to self-host soon.

I'll let you know if I can think of any new features.
